name: Run Tests

# Trigger workflow on push or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the workflow jobs
jobs:
  test:
    # Specify the environment
    runs-on: ubuntu-latest

    # Steps to run within this job
    steps:
      # Check out the code from the repo
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: '20'

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      - name: Run tests
        run: |
          pytest

